<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="style.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/68e2fe5586.js" crossorigin="anonymous"></script>
    <script src="aerius.js"></script>
    <title>Alojamientos</title>
</head>

<body class="body" id="hero">
    <header>
        <a href="inicio.html" class="logo">
            <img src="imagenes/logo con letra.png" alt="" width="150" class="logo">
        </a>
        <nav>
            <a href="paquetes.html" class="link">
                <i class="fa-solid fa-suitcase"></i>
                Paquetes
            </a>
            <a href="inicio.html" class="link">
                <i class="fa-solid fa-plane-departure"></i>
                Vuelos
            </a>
            <a href="alojamientos.html" class="link">
                <i class="fa-solid fa-house" style="color: #006a71;"></i>
                Alojamientos
            </a>
            <a href="ofertas.html" class="link">
                <i class="fa-solid fa-fire"></i>
                Ofertas
            </a>
            <a href="InicioSesion.html" class="buttons"><button>Iniciar Sesion</button></a>
            <a href="Registro.html" class="buttons"><button>Registrarse</button></a>
        </nav>


    </header>

    <div class="alojamientos">
        <div class="fondo">
            <!-- <img src="imagenes/camas.png" alt="" width="1900" /> -->
        </div>
        <div class="carda">
            <h1 id="tituloa">Alojamientos</h1>
            <div class="contenido-card">
                <div class="groupa">
                    <i class="fa-solid fa-house" id="icon"></i>
                    <input type="text" placeholder="¿A donde vas?" class="inputa">
                </div>
                <div class="groupa">
                    <i class="fa-solid fa-calendar-days" id="icon"></i>
                    <input type="date" placeholder="Destino" class="inputa">
                </div>

                <div class="groupa">
                    <i class="fa-solid fa-calendar-days" id="icon"></i>
                    <input type="date" placeholder="Destino" class="inputa">
                </div>
                <div class="pasajerosa">
                    <i class="fa-solid fa-person-walking-luggage" id="icon"></i>
                    <input type="text" placeholder="Personas" class="inputa"id="input-menu" readonly>
                </div>
                <div class="menu-verticala" id="menu-pasajeros" style="display: none;">
                    <div class="op-mv">
                      <div class="adultos">
                        <h4> Adultos </h4>
                        <button onclick="restarcontador1()"> - </button>
                        <p id="contador1">1</p>
                        <button onclick="sumarcontador1()">+</button>
                      </div>
                      <div class="niños">
                        <div class="tniños">
                          <h4> Niños </h4>
                        </div>
                        <div class="bniños">
                          <button onclick="restarcontador2()"> - </button>
                          <p id="contador2">0</p>
                          <button onclick="sumarcontador2()">+</button>
                        </div>
                      </div>
                      <button id="bap">Aplicar</button>
                    </div>
                  </div>
                <a href="busquedaalojamientos.html">
                    <button id="boton-card">Buscar</button>
                </a>

            </div>
        </div>
    </div>

    <div class="carteles">
        <div class="imagen-estatica">
            <img src="imagenes/cartel1.png" alt="" width="500">
        </div>
        <div class="slider-box">

            <ul>
                <li>
                    <img src="imagenes/cartel2.png" alt="" width="500">
                </li>
                <li>
                    <img src="imagenes/cartel3.png" alt="" width="500">
                </li>
                <li>
                    <img src="imagenes/cartel4.png" alt="" width="500">
                </li>
                <li>
                    <img src="imagenes/cartel5.png" alt="" width="500">
                </li>
                <li>
                    <img src="imagenes/cartel6.png" alt="" width="500">
                </li>

            </ul>
        </div>
    </div>


    <div class="footer-dark">
        <footer>
            <div class="containerf">
                <div class="row">
                    <div class="columna">
                        <h3>Servicios</h3>
                        <ul>
                            <li><a href="#">Diseño de Web</a></li>
                            <li><a href="#">Clase</a></li>
                            <li><a href="#">Hosteado</a></li>
                        </ul>
                    </div>
                    <div class="columna">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Compañia</a></li>
                            <li><a href="#">Acerca de nosotros</a></li>
                            <li><a href="#">Informacion</a></li>
                        </ul>
                    </div>
                    <div class="columna">
                        <h3>Aerius</h3>
                        <p> © 2025 Aerius. Todos los derechos reservados.</p>
                    </div>
                    <div class="col item social"></i></a><a href="#"><i
                                class="fa-brands fa-square-facebook"></i>></i></a><a href="#"><i
                                class="icon ion-social-snapchat"></i></a><a href="#"><i
                                class="fa-brands fa-instagram"></i>></i></a></div>
                </div>

            </div>
        </footer>
    </div>
</body>

</html>