<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="style.css" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet" />

  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/68e2fe5586.js" crossorigin="anonymous"></script>
  <title>Aerius</title>

</head>

<body class="body" id="hero">
  <header>
    <a href="inicio.html" class="logo">
      <img src="imagenes/logo con letra.png" alt="" width="150" class="logo" />
    </a>
    <nav>
      <a href="paquetes.html" class="link">
        <i class="fa-solid fa-suitcase" style="color: #006a71"></i>
        Paquetes
      </a>
      <a href="inicio.html" class="link">
        <i class="fa-solid fa-plane-departure"></i>
        Vuelos
      </a>
      <a href="alojamientos.html" class="link">
        <i class="fa-solid fa-house"></i>
        Alojamientos
      </a>
      <a href="ofertas.html" class="link">
        <i class="fa-solid fa-fire "></i>
        Ofertas
      </a>
      <a href="InicioSesion.html" class="buttons"><button>Iniciar Sesion</button></a>
      <a href="Registro.html" class="buttons"><button>Registrarse</button></a>
    </nav>
  </header>

  <h1>Filtros</h1>
  <h2>Equipaje</h2>
  <!-- From Uiverse.io by Na3ar-17 -->
  <div class="radio-inputt">
    <label class="label">
      <input type="radio" id="value-1" checked="" name="value-radio1" value="value-1" />
      <p class="text">Todos los equipajes</p>
    </label>
    <label class="label">
      <input type="radio" id="value-2" name="value-radio1" value="value-2" />
      <p class="text">Carry on</p>
    </label>
    <label class="label">
      <input type="radio" id="value-3" name="value-radio1" value="value-3" />
      <p class="text">Para despachar</p>
    </label>
  </div>



  <h2>Escalas</h2>

  <div class="radio-input">
    <label class="label">
      <input type="radio" id="value-2" checked="" name="value-radio2" value="value-2" />
      <p class="text">Todas las escalas</p>
    </label>
    <label class="label">
      <input type="radio" id="value-2" name="value-radio2" value="value-2" />
      <p class="text">Directo</p>
    </label>
    <label class="label">
      <input type="radio" id="value-3" name="value-radio2" value="value-3" />
      <p class="text">1 Escala</p>
    </label>
  </div>

  <h2>Aerolineas</h2>

  <div class="radio-input">
    <label class="label">
      <input type="radio" id="value-2" checked="" name="value-radio3" value="value-2" />
      <p class="text">Todas las aerolineas</p>
    </label>
    <label class="label">
      <input type="radio" id="value-2" name="value-radio3" value="value-2" />
      <img src="imagenes/ae.png" alt="" width="30" />
      <p class="text">Aerolineas</p>
    </label>
    <label class="label">
      <input type="radio" id="value-3" name="value-radio3" value="value-3" />
      <img src="https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/FO"
        alt="" width="30px">
      <img src="" alt="">
      <p class="text">FlyBondi</p>
    </label>
    <label class="label">
      <input type="radio" id="value-3" name="value-radio3" value="value-3" />
      <img src="imagenes/jet.png" alt="" width="30px">
      <p class="text">JetSmart</p>
    </label>
  </div>



  <div class="op-vuelos">

    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>IDA jue. 29 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" class="radiooo"> -->
            <img
              src="https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/FO"
              alt="" width="30px">
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
              <span class="material-symbols-outlined">
                luggage
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>

    </div>


    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>VUELTA sab. 31 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" checked> -->
            <img
              src="https://res.cloudinary.com/wego/f_auto,fl_lossy,w_1000,q_auto/v1480072078/flights/airlines_square/FO"
              alt="" width="30px">
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>


          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
              <span class="material-symbols-outlined">
                luggage
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>
      <div class="comprar">
        <h4>Precio total por pasajero</h4>
        <h2>$78.185</h2>
        <p>
          Inc. impuestos
          <br>
          y tasas
        </p>
        <p>
          Precio sin impuestos
          <br>
          nacionales: $ 72.116
        </p>
        <a href="eleccionaloj.html"><button >Elegir</button></a>

      </div>
    </div>
  </div>


  <div class="op-vuelos2">

    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>IDA jue. 29 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" class="radiooo"> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>

    </div>


    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>VUELTA sab. 31 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" checked> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>
      <div class="comprar">
        <h4>Precio total por pasajero</h4>
        <h2>$78.185</h2>
        <p>
          Inc. impuestos
          <br>
          y tasas
        </p>
        <p>
          Precio sin impuestos
          <br>
          nacionales: $ 72.116
        </p>
        <a href="eleccionaloj.html"><button >Elegir</button></a>

      </div>
    </div>
  </div>


  <div class="op-vuelos3">

    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>IDA jue. 29 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" class="radiooo"> -->
            <img src="imagenes/jet.png" alt="" width="30px">
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>

    </div>


    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>VUELTA sab. 31 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" checked> -->
            <img src="imagenes/jet.png" alt="" width="30px">
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>
      <div class="comprar">
        <h4>Precio total por pasajero</h4>
        <h2>$78.185</h2>
        <p>
          Inc. impuestos
          <br>
          y tasas
        </p>
        <p>
          Precio sin impuestos
          <br>
          nacionales: $ 72.116
        </p>
        <a href="eleccionaloj.html"><button >Elegir</button></a>

      </div>
    </div>
  </div>


  <div class="op-vuelos4">

    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>IDA jue. 29 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" class="radiooo"> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>

    </div>


    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>VUELTA sab. 31 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" checked> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>
      <div class="comprar">
        <h4>Precio total por pasajero</h4>
        <h2>$78.185</h2>
        <p>
          Inc. impuestos
          <br>
          y tasas
        </p>
        <p>
          Precio sin impuestos
          <br>
          nacionales: $ 72.116
        </p>
        <a href="eleccionaloj.html"><button >Elegir</button></a>

      </div>
    </div>
  </div>


  <div class="op-vuelos5">

    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>IDA jue. 29 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" class="radiooo"> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>

    </div>


    <div class="lll">
      <div class="aa">
        <div class="titulos-vuelos">
          <h4>VUELTA sab. 31 may. 2025</h4>
        </div>
      </div>
      <label class="eleccionvuelos">


        <div class="container-vuelos">
          <div class="titt">
            <!-- <input type="radio" name="radiobutton" id="" checked> -->
            <img src="imagenes/ae.png" alt="" width="30" />
          </div>

          <div class="titt">
            <h4>21:30</h4>
            <P>Cordoba - COR</P>
          </div>

          <div class="titt" id="directo">
            <p>- Directo -</p>
          </div>

          <div class="titt">
            <h4>22:45</h4>
            <P>Buenos Aires - AEP</P>
          </div>


          <div class="titt">
            <h4>Incluye</h4>
            <p>
              <span class="material-symbols-outlined">
                personal_bag
              </span>
              <span class="material-symbols-outlined">
                carry_on_bag
              </span>
            </p>


          </div>

          <div class="titt">
            <span class="material-symbols-outlined">
              keyboard_arrow_down
            </span>
          </div>

        </div>
      </label>
      <div class="comprar">
        <h4>Precio total por pasajero</h4>
        <h2>$78.185</h2>
        <p>
          Inc. impuestos
          <br>
          y tasas
        </p>
        <p>
          Precio sin impuestos
          <br>
          nacionales: $ 72.116
        </p>
        <a href="eleccionaloj.html"><button >Elegir</button></a>
        
      </div>
    </div>
  </div>



  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

  <div class="paginado">
    <button>
      <span class="material-symbols-outlined">
        chevron_left
      </span>
    </button>
    <h3>1</h3>
    <button>
      <span class="material-symbols-outlined">
        chevron_right
      </span>
    </button>
  </div>

  <div class="footer-dark">
    <footer>
      <div class="containerf">
        <div class="row">
          <div class="columna">
            <h3>Servicios</h3>
            <ul>
              <li><a href="#">Diseño de Web</a></li>
              <li><a href="#">Clase</a></li>
              <li><a href="#">Hosteado</a></li>
            </ul>
          </div>
          <div class="columna">
            <h3>About</h3>
            <ul>
              <li><a href="#">Compañia</a></li>
              <li><a href="#">Acerca de nosotros</a></li>
              <li><a href="#">Informacion</a></li>
            </ul>
          </div>
          <div class="columna">
            <h3>Aerius</h3>
            <p> © 2025 Aerius. Todos los derechos reservados.</p>
          </div>
          <div class="col item social"></i></a><a href="#"><i class="fa-brands fa-square-facebook"></i>></i></a><a
              href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i
                class="fa-brands fa-instagram"></i>></i></a></div>
        </div>

      </div>
    </footer>
  </div>



</body>