<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="style.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap"
      rel="stylesheet"
    />

    <link
      href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
      rel="stylesheet"
    />
    <script
      src="https://kit.fontawesome.com/68e2fe5586.js"
      crossorigin="anonymous"
    ></script>
    <title>Aerius</title>
  </head>
  <body>
    <header>
      <a href="inicio.html" class="logo">
        <img
          src="imagenes/logo con letra.png"
          alt=""
          width="150"
          class="logo"
        />
      </a>
      <nav>
        <a href="paquetes.html" class="link">
          <i class="fa-solid fa-suitcase"></i>
          Paquetes
        </a>
        <a href="inicio.html" class="link">
          <i class="fa-solid fa-plane-departure"></i>
          Vuelos
        </a>
        <a href="alojamientos.html" class="link">
          <i class="fa-solid fa-house" style="color: #006a71"></i>
          Alojamientos
        </a>
        <a href="ofertas.html" class="link">
          <i class="fa-solid fa-fire"></i>
          Ofertas
        </a>
        <a href="InicioSesion.html" class="buttons"
          ><button>Iniciar Sesion</button></a
        >
        <a href="Registro.html" class="buttons"><button>Registrarse</button></a>
      </nav>
    </header>

    <div class="fotos-aloj">
      <img
        src="https://media.staticontent.com/media/pictures/ca5bd8a9-3f04-46da-b7e4-b92336d58176/853x380?op=TRUNCATE&enlarge=false&gravity=ce_0_0&quality=80&dpr=1"
        alt=""
        class="img1"
      />
      <img
        src="https://media.staticontent.com/media/pictures/4fcffd75-839b-40e4-92cd-13bf3be47698/422x250?op=TRUNCATE&enlarge=false&gravity=ce_0_0&quality=80&dpr=1"
        alt=""
        class="img2"
      />
      <img
        src="https://media.staticontent.com/media/pictures/d61f5b2a-1d2c-4184-9800-52c86ff9d0cb/208x125?op=TRUNCATE&enlarge=false&gravity=ce_0_0&quality=80&dpr=1"
        alt=""
        class="img3"
      />
      <img
        src="https://media.staticontent.com/media/pictures/296f88c7-9588-4a9d-a0b6-e5516388260d/208x125?op=TRUNCATE&enlarge=false&gravity=ce_0_0&quality=80&dpr=1"
        alt=""
        class="img4"
      />
    </div>
  </body>
</html>
